// Package sidecar reads and writes the .<filename>.meta.yaml companion files
// that hold everything Kagaz learned about a document at ingest time.
//
// Sidecars are the reason queries are fast and offline: text is extracted once,
// never at query time. They are plain YAML dotfiles that sync through iCloud,
// survive being emailed around, and can be deleted at any time without harming
// the document.
package sidecar

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Suffix is appended to the (dot-prefixed) document name.
const Suffix = ".meta.yaml"

// MaxText caps how much extracted text a sidecar stores. Long documents keep
// their first MaxText bytes, which is enough for search and classification
// while keeping sidecars diffable.
const MaxText = 256 * 1024

// Meta is the sidecar document.
type Meta struct {
	ExtractedAt string            `yaml:"extracted_at"`
	OCREngine   string            `yaml:"ocr_engine"`
	Classifier  string            `yaml:"classifier"`
	DocType     string            `yaml:"doctype"`
	Category    string            `yaml:"category,omitempty"`
	Confidence  float64           `yaml:"confidence,omitempty"`
	Owners      []string          `yaml:"owners,omitempty"`
	Identifier  string            `yaml:"identifier,omitempty"`
	Year        int               `yaml:"year,omitempty"`
	Fields      map[string]string `yaml:"fields,omitempty"`
	SourceSHA   string            `yaml:"source_sha256"`
	TextTrunc   bool              `yaml:"text_truncated,omitempty"`
	Text        string            `yaml:"text,omitempty"`
}

// Path returns the sidecar path for a document.
func Path(doc string) string {
	return filepath.Join(filepath.Dir(doc), "."+filepath.Base(doc)+Suffix)
}

// IsSidecar reports whether path looks like a Kagaz sidecar.
func IsSidecar(path string) bool {
	base := filepath.Base(path)
	return strings.HasPrefix(base, ".") && strings.HasSuffix(base, Suffix)
}

// DocumentFor returns the document a sidecar belongs to.
func DocumentFor(sidecarPath string) string {
	base := filepath.Base(sidecarPath)
	base = strings.TrimSuffix(strings.TrimPrefix(base, "."), Suffix)
	return filepath.Join(filepath.Dir(sidecarPath), base)
}

// Read loads the sidecar for a document. A missing sidecar returns
// (nil, nil): most of the vault legitimately has none.
func Read(doc string) (*Meta, error) {
	return ReadFile(Path(doc))
}

// ReadFile loads a sidecar by its own path.
func ReadFile(path string) (*Meta, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var m Meta
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &m, nil
}

// Write saves the sidecar next to its document, truncating stored text to
// MaxText.
func Write(doc string, m *Meta) error {
	if m.ExtractedAt == "" {
		m.ExtractedAt = time.Now().Format("2006-01-02")
	}
	if len(m.Text) > MaxText {
		m.Text = m.Text[:MaxText]
		m.TextTrunc = true
	}
	data, err := yaml.Marshal(m)
	if err != nil {
		return err
	}
	header := "# Generated by kagaz at ingest. Safe to delete; regenerate with `kagaz ingest --reindex`.\n"
	return os.WriteFile(Path(doc), append([]byte(header), data...), 0o644)
}

// Remove deletes a sidecar if present.
func Remove(doc string) error {
	err := os.Remove(Path(doc))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// Stale reports whether the sidecar no longer matches the document's content
// hash, meaning the document was edited or replaced since ingest.
func (m *Meta) Stale(currentSHA string) bool {
	return m != nil && m.SourceSHA != "" && currentSHA != "" && m.SourceSHA != currentSHA
}

// Field returns an extracted field.
func (m *Meta) Field(name string) (string, bool) {
	if m == nil || m.Fields == nil {
		return "", false
	}
	v, ok := m.Fields[name]
	return v, ok
}
