package cli

import (
	"context"
	"fmt"
	"io"
	"path/filepath"
	"strings"
	"time"

	"github.com/getkagaz/kagaz/internal/vaultkit/config"
	"github.com/getkagaz/kagaz/internal/vaultkit/doctypes"
	"github.com/getkagaz/kagaz/internal/vaultkit/ingest"
	"github.com/getkagaz/kagaz/internal/vaultkit/ocr"
	"github.com/getkagaz/kagaz/internal/vaultkit/search"
	"github.com/getkagaz/kagaz/internal/vaultkit/sidecar"
	"github.com/spf13/cobra"
)

// IngestPayload is the `kagaz ingest --json` body. The same shape carries a
// proposal (nothing executed) and a result (executed true), because they are
// the same batch at two moments, not two different things.
type IngestPayload struct {
	// Proposals is every proposal the analysis produced, numbered from 1.
	Proposals []ingest.Proposal `json:"proposals"`
	// Selected are the 1-based indices approved for execution.
	Selected []int `json:"selected,omitempty"`
	// Executed reports whether anything was actually moved.
	Executed bool `json:"executed"`
	// Filed are the documents that moved.
	Filed []MoveRecord `json:"filed,omitempty"`
	// Sidecars are the sidecar files written.
	Sidecars []string `json:"sidecars,omitempty"`
	// Manifest is the batch manifest `kagaz rollback` reverses.
	Manifest string `json:"manifest,omitempty"`
	// Reindexed lists documents whose sidecar was regenerated by --reindex.
	Reindexed []string `json:"reindexed,omitempty"`
	// Guidance is the CLI's advice for proposals that could not be filed: what
	// caused it and which command actually works next.
	Guidance []Guidance `json:"guidance,omitempty"`
}

// Guidance is what to do about one proposal that was not filed. The pipeline
// says why it stopped; this says what the user should type, which is a
// different question and the CLI's job to answer.
type Guidance struct {
	// Source is the file the advice is about.
	Source string `json:"source"`
	// Cause names the underlying limitation in plain terms.
	Cause string `json:"cause"`
	// NextStep is a command that will actually work on this file.
	NextStep string `json:"next_step"`
}

// guidanceFor builds the advice for every proposal that was skipped.
//
// The bare `kagaz move <src>` that a skipped proposal invites is a dead end for
// exactly the file that produced it: with no text extractor the filename does
// not match the grammar and no sidecar exists, so the conventional path cannot
// be derived and move refuses. The destination-explicit form is the one that
// works, and the extractor is the reason, so both are said here.
func guidanceFor(proposals []ingest.Proposal) []Guidance {
	var out []Guidance
	for _, p := range proposals {
		if !p.Skip {
			continue
		}
		cause := p.SkipReason
		ext := strings.ToLower(filepath.Ext(p.Source))
		if noTextExtracted(p) {
			// Name the format, not the machine. "no text extractor on this
			// machine" reads as a missing tool the user could install, which
			// for a format Kagaz simply does not read is advice that can never
			// come true. Kagaz reads what readableFormats lists; anything else
			// is out of scope by design, not by configuration.
			switch {
			case ext == "":
				cause = "Kagaz does not read files without an extension (it reads " + readableFormats + "), so there was nothing to classify"
			case needsTextUtil(ext):
				// A real missing tool, but not one `kagaz doctor` can talk the
				// user into installing: textutil ships with macOS and exists
				// nowhere else, so say which machine can read the file.
				cause = fmt.Sprintf("reading %s needs macOS's /usr/bin/textutil, which is not on this machine; ingest the file on a Mac, or re-save it as .docx or .txt and ingest that", ext)
			case wrongContainer(p) != "":
				// The extractor already said the bytes are not the format the
				// name claims, and that warning is printed directly above this
				// line. Sending the user to `kagaz doctor` here would contradict
				// it: doctor would report the tier present and correct, and the
				// user would go hunting for a tooling problem that does not
				// exist. No machine can turn these bytes into that format.
				cause = fmt.Sprintf(
					"this %s is not %s inside, whatever its name says, so there was nothing to extract; "+
						"the tier that reads %s ran and found some other format's bytes -- give the file the extension it actually is, or re-save it from the app that made it",
					ext, wrongContainer(p), ext)
			case readableExt(ext):
				// A format Kagaz does understand, so this really is a missing
				// tool or an unreadable file, and `kagaz doctor` can help.
				cause = fmt.Sprintf("no text could be extracted from this %s (run kagaz doctor to see which extraction tiers are available), so there was nothing to classify", ext)
			default:
				cause = fmt.Sprintf("Kagaz does not read %s files (it reads %s), so there was nothing to classify", ext, readableFormats)
			}
		}
		next := fmt.Sprintf("kagaz move %s <destination>   (the destination must be given: %s has neither a conventional filename nor a sidecar, so kagaz cannot derive one)",
			shellQuote(p.Source), filepath.Base(p.Source))
		if p.DocType == doctypes.Unclassified && !noTextExtracted(p) {
			// "kagaz read it and could not tell" now has an answer that does not
			// require the user to know the vault's naming grammar: say what the
			// document is and let the conventions build the path, exactly as they
			// do for a classified one.
			//
			// Only when there was text. A file Kagaz cannot read at all would be
			// filed with an empty sidecar and an identifier scraped off its name,
			// which is not what the user wants offered first; the cause above says
			// the format is the problem, and the destination-explicit `kagaz move`
			// remains the answer that matches it.
			next = fmt.Sprintf("kagaz ingest %s --set-doctype <name> --yes   (say what it is; kagaz builds the destination from its own conventions and records the classification as human)",
				shellQuote(p.Source))
		}
		out = append(out, Guidance{Source: p.Source, Cause: cause, NextStep: next})
	}
	return out
}

// teachHint is the one line that says a human assignment does not teach the
// vault anything by itself.
//
// It is a suggestion and nothing else. Kagaz does not edit a user's vault.yaml
// on their behalf -- a tool that quietly rewrites your configuration because it
// noticed a pattern is exactly the kind of thing this project refuses to be --
// so the next-time fix is named, and the user decides.
func teachHint(docType string, proposals []ingest.Proposal) []string {
	if docType == "" {
		return nil
	}
	n := 0
	for _, p := range proposals {
		if p.Classifier == ingest.ClassifierHuman && !p.Skip {
			n++
		}
	}
	if n == 0 {
		return nil
	}
	return []string{fmt.Sprintf(
		"you assigned %q to %d document(s); Kagaz does not learn from that on its own. "+
			"To have it recognise them next time, add a distinctive phrase from these documents to the %q entry under doctypes: in vault.yaml "+
			"(kagaz never edits your config for you)", docType, n, docType)}
}

// readableFormats is the one place the "what Kagaz reads" sentence is written,
// so a new extraction tier cannot leave a guidance string quietly lying. It is
// kept in step with readableExt: every extension named here is one readableExt
// accepts, and TestReadableFormatsMatchesReadableExt fails if they drift.
const readableFormats = "PDFs, images, plain text, Office .docx/.xlsx/.pptx, " +
	"and the legacy .doc/.rtf/.rtfd/.odt/.wordml/.xls/.ppt"

// wrongContainer describes the container a skipped file was supposed to be but
// is not, when the extractor diagnosed exactly that, or "" when it did not.
//
// This is the one case where "no text could be extracted" must not send the
// user to `kagaz doctor`: the file is not the format its name claims, every
// tier is present and working, and the advice would contradict the warning
// printed immediately above it.
func wrongContainer(p ingest.Proposal) string {
	for _, w := range p.Warnings {
		switch {
		case strings.Contains(w, ocr.ErrNotCFB.Error()):
			return "an OLE2 compound file (which is what a .xls or .ppt is)"
		case strings.Contains(w, ocr.ErrNotOOXML.Error()):
			return "a ZIP of XML parts (which is what a .docx, .xlsx or .pptx is)"
		}
	}
	return ""
}

// readableExt reports whether ext names a format Kagaz has an extraction tier
// for, so guidance can tell "we don't read this" apart from "we read this and
// got nothing". ext is lowercased and includes the dot.
func readableExt(ext string) bool {
	for _, list := range [][]string{
		ocr.PlainTextExtensions,
		ocr.OfficeExtensions,
		ocr.TextUtilExtensions,
		ocr.CompoundOfficeExtensions,
	} {
		for _, known := range list {
			if ext == known {
				return true
			}
		}
	}
	switch ext {
	case ".pdf", ".jpg", ".jpeg", ".png", ".tif", ".tiff", ".heic", ".heif", ".gif", ".bmp", ".webp":
		return true
	}
	return false
}

// needsTextUtil reports whether ext is one only the textutil tier reads *and*
// textutil is missing here. It separates "this machine cannot read it" from
// "Kagaz cannot read it", which are different pieces of advice: the first is
// answered by a Mac, the second only by re-saving the file.
func needsTextUtil(ext string) bool {
	for _, known := range ocr.TextUtilExtensions {
		if ext == known {
			return !(&ocr.TextUtil{}).Available()
		}
	}
	return false
}

// noTextExtracted reports whether extraction produced nothing for this file.
func noTextExtracted(p ingest.Proposal) bool {
	if p.OCREngine == "" || p.OCREngine == "none" {
		return true
	}
	for _, w := range p.Warnings {
		if strings.Contains(w, ocr.ErrNoText.Error()) {
			return true
		}
	}
	return false
}

// shellQuote quotes a path for a command a user is meant to paste.
func shellQuote(s string) string {
	if strings.ContainsAny(s, " \t\"'$`\\") {
		return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
	}
	return s
}

// tidyReasons collapses a wrapped error that repeats itself, as
// "no text extracted: no text extracted" does when a sentinel is wrapped with
// its own text. Saying it twice reads like two different problems.
func tidyReasons(text string) string {
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		parts := strings.Split(line, ": ")
		kept := []string{parts[0]}
		for j := 1; j < len(parts); j++ {
			if strings.TrimSpace(parts[j]) == unlabel(parts[j-1]) {
				continue
			}
			kept = append(kept, parts[j])
		}
		lines[i] = strings.Join(kept, ": ")
	}
	return strings.Join(lines, "\n")
}

// unlabel strips the preview's leading gutter label ("   warn  ") from a
// segment, so that "warn  no text extracted: no text extracted" is recognised
// as the same sentence said twice.
func unlabel(s string) string {
	if i := strings.LastIndex(s, "  "); i >= 0 {
		return strings.TrimSpace(s[i:])
	}
	return strings.TrimSpace(s)
}

func newIngestCommand(rt *Runtime) *cobra.Command {
	var (
		selectExpr string
		reindex    bool
		mut        mutationFlags
		set        ingest.Overrides
	)

	cmd := &cobra.Command{
		Use:   "ingest [path]...",
		Short: "Propose a home for loose files, then file them on approval",
		Long: "ingest runs OCR, classification, extraction and inference over each path and\n" +
			"presents a numbered batch review. Approving executes the whole batch through\n" +
			"move.Engine under a single manifest.\n\n" +
			"At the review prompt (or via --select) answer `all`, `none`, or a subset such\n" +
			"as `1,3-5`. --reindex regenerates the sidecars of documents already filed in\n" +
			"the vault instead of filing new ones; it never moves a document.\n\n" +
			"When a document comes back unclassified -- the honest answer when no tier can\n" +
			"tell what it is -- say what it is yourself: --set-doctype files every path in\n" +
			"the invocation as that doctype, and --set-owner/--set-identifier/--set-year\n" +
			"replace the matching inference. The category always comes from the vault's\n" +
			"doctype catalog, never from a flag, and the sidecar records the classification\n" +
			"as `human` so a decision you made is never filed away as one a model made.",
		Args: cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := rt.Config()
			if err != nil {
				return err
			}
			pipeline, err := ingest.New(cfg)
			if err != nil {
				return err
			}

			paths := args
			if reindex && !set.Empty() {
				// --reindex rewrites the sidecar of a document already filed, and
				// never moves it. Stamping a stated doctype into that sidecar
				// would leave the document sitting at a path its own facts no
				// longer agree with, which is a re-filing decision the user has
				// not been shown. `kagaz move` is where that decision is made.
				return fmt.Errorf("--set-* cannot be combined with --reindex: reindex rewrites the sidecar of a document that is already filed and never moves it, " +
					"so a stated doctype would leave it at the wrong path. Use `kagaz move` to re-file a filed document")
			}
			if reindex {
				if len(paths) == 0 {
					paths, err = vaultDocuments(cmd.Context(), cfg)
					if err != nil {
						return err
					}
				}
				if len(paths) == 0 {
					return rt.Emit(&Response{
						Command: "ingest", Status: StatusOK,
						Payload: IngestPayload{Proposals: []ingest.Proposal{}}, Human: humanIngest,
					})
				}
			}
			if len(paths) == 0 {
				return fmt.Errorf("nothing to ingest: name one or more files or directories")
			}

			rt.Printf("analysing %d path(s)…\n", len(paths))
			proposals, err := pipeline.AnalyzeWith(cmd.Context(), paths, set)
			if err != nil {
				return err
			}
			payload := IngestPayload{Proposals: proposals}
			if payload.Proposals == nil {
				payload.Proposals = []ingest.Proposal{}
			}
			payload.Guidance = guidanceFor(payload.Proposals)
			teach := teachHint(set.DocType, payload.Proposals)

			if reindex {
				return runReindex(rt, cfg, payload, &mut)
			}

			// Selection is the approval: naming which proposals to execute is a
			// stronger statement of consent than a bare yes, so an explicit
			// --select stands in for it. Everything else routes through the
			// shared approval rules.
			var indices []int
			switch {
			case mut.proposeOnly:
				return rt.Emit(&Response{
					Command: "ingest", Status: StatusProposed, Payload: payload, Human: previewIngest,
					Warnings: teach,
				})
			case selectExpr != "":
				indices, err = ingest.ParseSelection(selectExpr, len(proposals))
				if err != nil {
					return err
				}
			case mut.yes:
				indices, err = ingest.ParseSelection(ingest.SelectAll, len(proposals))
				if err != nil {
					return err
				}
			case rt.JSON || !rt.Interactive():
				return rt.Emit(&Response{
					Command: "ingest", Status: StatusConfirmationRequired, Payload: payload,
					Human: previewIngest, Exit: ExitConfirmationRequired,
					Warnings: append([]string{"nothing was changed: re-run with --select all (or a subset like 1,3-5), or --yes"}, teach...),
				})
			default:
				if err := previewIngest(rt.Out, payload); err != nil {
					return err
				}
				answer, perr := rt.Prompt(fmt.Sprintf("\nFile which of the %d proposals? [all/none/1,3-5] ", len(proposals)))
				if perr != nil {
					return perr
				}
				indices, err = ingest.ParseSelection(answer, len(proposals))
				if err != nil {
					return err
				}
			}

			payload.Selected = indices
			if len(indices) == 0 {
				return rt.Emit(&Response{
					Command: "ingest", Status: StatusProposed, Payload: payload, Human: humanIngest,
					Warnings: teach,
				})
			}

			res, err := pipeline.Execute(ingest.Select(proposals, indices))
			if res != nil {
				// Executed reports whether anything really moved, not whether
				// the attempt was made: a batch in which every proposal was
				// skipped filed nothing, and saying otherwise would let a
				// caller believe its documents are somewhere they are not.
				payload.Executed = len(res.Filed) > 0
				payload.Manifest = res.ManifestPath()
				payload.Sidecars = res.Sidecars
				for _, prop := range res.Filed {
					payload.Filed = append(payload.Filed, MoveRecord{From: prop.Source, To: prop.Dest})
				}
			}
			if err != nil {
				return err
			}
			warnings := res.Warnings
			if !payload.Executed {
				warnings = append(warnings,
					"nothing was filed: every selected proposal was skipped (see skip_reason on each)")
			}
			warnings = append(warnings, teach...)
			return rt.Emit(&Response{
				Command: "ingest", Status: StatusOK, Payload: payload,
				Warnings: warnings, Human: humanIngest,
			})
		},
	}

	f := cmd.Flags()
	f.StringVar(&selectExpr, "select", "", "which proposals to file: all, none, or a subset like 1,3-5")
	f.BoolVar(&reindex, "reindex", false, "regenerate sidecars for documents already in the vault")
	f.StringVar(&set.DocType, "set-doctype", "", "file every named path as this doctype instead of classifying it (must exist in the vault's catalog)")
	// A repeated flag rather than a comma-separated list: a person's display
	// name is free text that may itself contain a comma or a semicolon, and a
	// separator that can appear inside a value is a parser that will one day
	// split somebody's name in half. StringArray does not split on commas.
	f.StringArrayVar(&set.Owners, "set-owner", nil, "owner for every named path, by display name or tag; repeat the flag for several owners")
	f.StringVar(&set.Identifier, "set-identifier", "", "identifier for every named path, instead of inferring one")
	f.IntVar(&set.Year, "set-year", 0, "four-digit year for every named path, instead of inferring one")
	mut.register(cmd)
	return cmd
}

// runReindex rewrites sidecars in place.
//
// It deliberately does not go through move.Engine: nothing moves. A document
// whose filename no longer matches its facts is reported rather than relocated,
// because re-filing on the back of a re-extraction is a second decision the
// user has not been shown — `kagaz lint --fix` and `kagaz move` are where that
// decision is made.
func runReindex(rt *Runtime, cfg *config.Config, payload IngestPayload, mut *mutationFlags) error {
	var targets []ingest.Proposal
	for _, prop := range payload.Proposals {
		if prop.Skip {
			continue
		}
		targets = append(targets, prop)
		payload.Reindexed = append(payload.Reindexed, prop.Source)
	}
	if len(targets) == 0 {
		return rt.Emit(&Response{Command: "ingest", Status: StatusOK, Payload: payload, Human: humanIngest})
	}

	approved, resp := mut.approve(rt, "ingest", payload, previewReindex)
	if !approved {
		return rt.Emit(resp)
	}

	var warnings []string
	written := make([]string, 0, len(targets))
	for _, prop := range targets {
		meta := &sidecar.Meta{
			ExtractedAt: nowStamp(),
			OCREngine:   prop.OCREngine,
			Classifier:  prop.Classifier,
			DocType:     prop.DocType,
			Category:    prop.Category,
			Confidence:  prop.Confidence,
			Owners:      prop.Owners,
			Identifier:  prop.Identifier,
			Year:        prop.Year,
			Fields:      prop.Fields,
			SourceSHA:   prop.SourceSHA,
			Text:        prop.Text,
		}
		if err := sidecar.Write(prop.Source, meta); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: sidecar not written: %v", filepath.Base(prop.Source), err))
			continue
		}
		written = append(written, sidecar.Path(prop.Source))
		if prop.Dest != "" && prop.Dest != prop.Source {
			warnings = append(warnings, fmt.Sprintf("%s is not at its conventional path (%s); `kagaz lint --fix` or `kagaz move` will re-file it",
				prop.Source, prop.Dest))
		}
	}
	payload.Sidecars = written
	payload.Reindexed = payload.Reindexed[:0]
	for _, p := range written {
		payload.Reindexed = append(payload.Reindexed, sidecar.DocumentFor(p))
	}
	return rt.Emit(&Response{
		Command: "ingest", Status: StatusOK, Payload: payload,
		Warnings: warnings, Human: humanIngest,
	})
}

// vaultDocuments lists every document currently filed in the vault.
func vaultDocuments(ctx context.Context, cfg *config.Config) ([]string, error) {
	searcher, err := search.New(cfg)
	if err != nil {
		return nil, err
	}
	tree, err := searcher.Scan(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(tree.Documents))
	for i := range tree.Documents {
		if tree.Documents[i].Evicted {
			continue
		}
		out = append(out, tree.Documents[i].Path)
	}
	return out, nil
}

func previewIngest(w io.Writer, payload any) error {
	p, ok := payload.(IngestPayload)
	if !ok {
		return fmt.Errorf("ingest: unexpected payload %T", payload)
	}
	if len(p.Proposals) == 0 {
		fmt.Fprintln(w, "nothing to propose")
		return nil
	}
	advice := map[string]Guidance{}
	for _, g := range p.Guidance {
		advice[g.Source] = g
	}
	for _, prop := range p.Proposals {
		fmt.Fprint(w, tidyReasons(prop.Preview()))
		if g, ok := advice[prop.Source]; ok {
			fmt.Fprintf(w, "   why   %s\n", g.Cause)
			fmt.Fprintf(w, "   next  %s\n", g.NextStep)
		}
	}
	return nil
}

func previewReindex(w io.Writer, payload any) error {
	p, ok := payload.(IngestPayload)
	if !ok {
		return fmt.Errorf("ingest: unexpected payload %T", payload)
	}
	fmt.Fprintf(w, "regenerate %d sidecar(s):\n", len(p.Reindexed))
	for _, path := range p.Reindexed {
		fmt.Fprintf(w, "  %s\n", path)
	}
	return nil
}

func humanIngest(w io.Writer, payload any) error {
	p, ok := payload.(IngestPayload)
	if !ok {
		return fmt.Errorf("ingest: unexpected payload %T", payload)
	}
	if len(p.Reindexed) > 0 || len(p.Sidecars) > 0 && !p.Executed {
		fmt.Fprintf(w, "regenerated %d sidecar(s)\n", len(p.Sidecars))
		return nil
	}
	if !p.Executed {
		if len(p.Proposals) == 0 {
			fmt.Fprintln(w, "nothing to propose")
			return nil
		}
		return previewIngest(w, payload)
	}
	for _, m := range p.Filed {
		fmt.Fprintf(w, "filed %s\n   -> %s\n", filepath.Base(m.From), m.To)
	}
	fmt.Fprintf(w, "\n%d document(s) filed, %d sidecar(s) written\n", len(p.Filed), len(p.Sidecars))
	if p.Manifest != "" {
		fmt.Fprintf(w, "manifest: %s (reverse with `kagaz rollback %s`)\n", p.Manifest, filepath.Base(p.Manifest))
	}
	return nil
}

// summarizeProposal is the one-line form used by `watch`, which reports many
// small batches rather than one reviewed batch.
func summarizeProposal(p ingest.Proposal) string {
	if p.Skip {
		return tidyReasons(fmt.Sprintf("%s: skipped (%s)", filepath.Base(p.Source), p.SkipReason))
	}
	return fmt.Sprintf("%s -> %s [%s %.2f]", filepath.Base(p.Source), p.Dest, p.DocType, p.Confidence)
}

// nowStamp is the date form sidecars record.
func nowStamp() string { return time.Now().Format("2006-01-02") }
