package cli

import (
	"context"
	"fmt"
	"io"
	"path/filepath"
	"strings"
	"time"

	"github.com/getkagaz/kagaz/internal/vaultkit/config"
	"github.com/getkagaz/kagaz/internal/vaultkit/ingest"
	"github.com/getkagaz/kagaz/internal/vaultkit/ocr"
	"github.com/getkagaz/kagaz/internal/vaultkit/search"
	"github.com/getkagaz/kagaz/internal/vaultkit/sidecar"
	"github.com/spf13/cobra"
)

// IngestPayload is the `kagaz ingest --json` body. The same shape carries a
// proposal (nothing executed) and a result (executed true), because they are
// the same batch at two moments, not two different things.
type IngestPayload struct {
	// Proposals is every proposal the analysis produced, numbered from 1.
	Proposals []ingest.Proposal `json:"proposals"`
	// Selected are the 1-based indices approved for execution.
	Selected []int `json:"selected,omitempty"`
	// Executed reports whether anything was actually moved.
	Executed bool `json:"executed"`
	// Filed are the documents that moved.
	Filed []MoveRecord `json:"filed,omitempty"`
	// Sidecars are the sidecar files written.
	Sidecars []string `json:"sidecars,omitempty"`
	// Manifest is the batch manifest `kagaz rollback` reverses.
	Manifest string `json:"manifest,omitempty"`
	// Reindexed lists documents whose sidecar was regenerated by --reindex.
	Reindexed []string `json:"reindexed,omitempty"`
	// Guidance is the CLI's advice for proposals that could not be filed: what
	// caused it and which command actually works next.
	Guidance []Guidance `json:"guidance,omitempty"`
}

// Guidance is what to do about one proposal that was not filed. The pipeline
// says why it stopped; this says what the user should type, which is a
// different question and the CLI's job to answer.
type Guidance struct {
	// Source is the file the advice is about.
	Source string `json:"source"`
	// Cause names the underlying limitation in plain terms.
	Cause string `json:"cause"`
	// NextStep is a command that will actually work on this file.
	NextStep string `json:"next_step"`
}

// guidanceFor builds the advice for every proposal that was skipped.
//
// The bare `kagaz move <src>` that a skipped proposal invites is a dead end for
// exactly the file that produced it: with no text extractor the filename does
// not match the grammar and no sidecar exists, so the conventional path cannot
// be derived and move refuses. The destination-explicit form is the one that
// works, and the extractor is the reason, so both are said here.
func guidanceFor(proposals []ingest.Proposal) []Guidance {
	var out []Guidance
	for _, p := range proposals {
		if !p.Skip {
			continue
		}
		cause := p.SkipReason
		ext := strings.ToLower(filepath.Ext(p.Source))
		if noTextExtracted(p) {
			cause = fmt.Sprintf("no text extractor for %s on this machine, so there was nothing to classify", ext)
			if ext == "" {
				cause = "no text extractor for this file type on this machine, so there was nothing to classify"
			}
		}
		out = append(out, Guidance{
			Source: p.Source,
			Cause:  cause,
			NextStep: fmt.Sprintf("kagaz move %s <destination>   (the destination must be given: %s has neither a conventional filename nor a sidecar, so kagaz cannot derive one)",
				shellQuote(p.Source), filepath.Base(p.Source)),
		})
	}
	return out
}

// noTextExtracted reports whether extraction produced nothing for this file.
func noTextExtracted(p ingest.Proposal) bool {
	if p.OCREngine == "" || p.OCREngine == "none" {
		return true
	}
	for _, w := range p.Warnings {
		if strings.Contains(w, ocr.ErrNoText.Error()) {
			return true
		}
	}
	return false
}

// shellQuote quotes a path for a command a user is meant to paste.
func shellQuote(s string) string {
	if strings.ContainsAny(s, " \t\"'$`\\") {
		return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
	}
	return s
}

// tidyReasons collapses a wrapped error that repeats itself, as
// "no text extracted: no text extracted" does when a sentinel is wrapped with
// its own text. Saying it twice reads like two different problems.
func tidyReasons(text string) string {
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		parts := strings.Split(line, ": ")
		kept := []string{parts[0]}
		for j := 1; j < len(parts); j++ {
			if strings.TrimSpace(parts[j]) == unlabel(parts[j-1]) {
				continue
			}
			kept = append(kept, parts[j])
		}
		lines[i] = strings.Join(kept, ": ")
	}
	return strings.Join(lines, "\n")
}

// unlabel strips the preview's leading gutter label ("   warn  ") from a
// segment, so that "warn  no text extracted: no text extracted" is recognised
// as the same sentence said twice.
func unlabel(s string) string {
	if i := strings.LastIndex(s, "  "); i >= 0 {
		return strings.TrimSpace(s[i:])
	}
	return strings.TrimSpace(s)
}

func newIngestCommand(rt *Runtime) *cobra.Command {
	var (
		selectExpr string
		reindex    bool
		mut        mutationFlags
	)

	cmd := &cobra.Command{
		Use:   "ingest [path]...",
		Short: "Propose a home for loose files, then file them on approval",
		Long: "ingest runs OCR, classification, extraction and inference over each path and\n" +
			"presents a numbered batch review. Approving executes the whole batch through\n" +
			"move.Engine under a single manifest.\n\n" +
			"At the review prompt (or via --select) answer `all`, `none`, or a subset such\n" +
			"as `1,3-5`. --reindex regenerates the sidecars of documents already filed in\n" +
			"the vault instead of filing new ones; it never moves a document.",
		Args: cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := rt.Config()
			if err != nil {
				return err
			}
			pipeline, err := ingest.New(cfg)
			if err != nil {
				return err
			}

			paths := args
			if reindex {
				if len(paths) == 0 {
					paths, err = vaultDocuments(cmd.Context(), cfg)
					if err != nil {
						return err
					}
				}
				if len(paths) == 0 {
					return rt.Emit(&Response{
						Command: "ingest", Status: StatusOK,
						Payload: IngestPayload{Proposals: []ingest.Proposal{}}, Human: humanIngest,
					})
				}
			}
			if len(paths) == 0 {
				return fmt.Errorf("nothing to ingest: name one or more files or directories")
			}

			rt.Printf("analysing %d path(s)…\n", len(paths))
			proposals, err := pipeline.Analyze(cmd.Context(), paths)
			if err != nil {
				return err
			}
			payload := IngestPayload{Proposals: proposals}
			if payload.Proposals == nil {
				payload.Proposals = []ingest.Proposal{}
			}
			payload.Guidance = guidanceFor(payload.Proposals)

			if reindex {
				return runReindex(rt, cfg, payload, &mut)
			}

			// Selection is the approval: naming which proposals to execute is a
			// stronger statement of consent than a bare yes, so an explicit
			// --select stands in for it. Everything else routes through the
			// shared approval rules.
			var indices []int
			switch {
			case mut.proposeOnly:
				return rt.Emit(&Response{
					Command: "ingest", Status: StatusProposed, Payload: payload, Human: previewIngest,
				})
			case selectExpr != "":
				indices, err = ingest.ParseSelection(selectExpr, len(proposals))
				if err != nil {
					return err
				}
			case mut.yes:
				indices, err = ingest.ParseSelection(ingest.SelectAll, len(proposals))
				if err != nil {
					return err
				}
			case rt.JSON || !rt.Interactive():
				return rt.Emit(&Response{
					Command: "ingest", Status: StatusConfirmationRequired, Payload: payload,
					Human: previewIngest, Exit: ExitConfirmationRequired,
					Warnings: []string{"nothing was changed: re-run with --select all (or a subset like 1,3-5), or --yes"},
				})
			default:
				if err := previewIngest(rt.Out, payload); err != nil {
					return err
				}
				answer, perr := rt.Prompt(fmt.Sprintf("\nFile which of the %d proposals? [all/none/1,3-5] ", len(proposals)))
				if perr != nil {
					return perr
				}
				indices, err = ingest.ParseSelection(answer, len(proposals))
				if err != nil {
					return err
				}
			}

			payload.Selected = indices
			if len(indices) == 0 {
				return rt.Emit(&Response{
					Command: "ingest", Status: StatusProposed, Payload: payload, Human: humanIngest,
				})
			}

			res, err := pipeline.Execute(ingest.Select(proposals, indices))
			if res != nil {
				// Executed reports whether anything really moved, not whether
				// the attempt was made: a batch in which every proposal was
				// skipped filed nothing, and saying otherwise would let a
				// caller believe its documents are somewhere they are not.
				payload.Executed = len(res.Filed) > 0
				payload.Manifest = res.ManifestPath()
				payload.Sidecars = res.Sidecars
				for _, prop := range res.Filed {
					payload.Filed = append(payload.Filed, MoveRecord{From: prop.Source, To: prop.Dest})
				}
			}
			if err != nil {
				return err
			}
			warnings := res.Warnings
			if !payload.Executed {
				warnings = append(warnings,
					"nothing was filed: every selected proposal was skipped (see skip_reason on each)")
			}
			return rt.Emit(&Response{
				Command: "ingest", Status: StatusOK, Payload: payload,
				Warnings: warnings, Human: humanIngest,
			})
		},
	}

	f := cmd.Flags()
	f.StringVar(&selectExpr, "select", "", "which proposals to file: all, none, or a subset like 1,3-5")
	f.BoolVar(&reindex, "reindex", false, "regenerate sidecars for documents already in the vault")
	mut.register(cmd)
	return cmd
}

// runReindex rewrites sidecars in place.
//
// It deliberately does not go through move.Engine: nothing moves. A document
// whose filename no longer matches its facts is reported rather than relocated,
// because re-filing on the back of a re-extraction is a second decision the
// user has not been shown — `kagaz lint --fix` and `kagaz move` are where that
// decision is made.
func runReindex(rt *Runtime, cfg *config.Config, payload IngestPayload, mut *mutationFlags) error {
	var targets []ingest.Proposal
	for _, prop := range payload.Proposals {
		if prop.Skip {
			continue
		}
		targets = append(targets, prop)
		payload.Reindexed = append(payload.Reindexed, prop.Source)
	}
	if len(targets) == 0 {
		return rt.Emit(&Response{Command: "ingest", Status: StatusOK, Payload: payload, Human: humanIngest})
	}

	approved, resp := mut.approve(rt, "ingest", payload, previewReindex)
	if !approved {
		return rt.Emit(resp)
	}

	var warnings []string
	written := make([]string, 0, len(targets))
	for _, prop := range targets {
		meta := &sidecar.Meta{
			ExtractedAt: nowStamp(),
			OCREngine:   prop.OCREngine,
			Classifier:  prop.Classifier,
			DocType:     prop.DocType,
			Category:    prop.Category,
			Confidence:  prop.Confidence,
			Owners:      prop.Owners,
			Identifier:  prop.Identifier,
			Year:        prop.Year,
			Fields:      prop.Fields,
			SourceSHA:   prop.SourceSHA,
			Text:        prop.Text,
		}
		if err := sidecar.Write(prop.Source, meta); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: sidecar not written: %v", filepath.Base(prop.Source), err))
			continue
		}
		written = append(written, sidecar.Path(prop.Source))
		if prop.Dest != "" && prop.Dest != prop.Source {
			warnings = append(warnings, fmt.Sprintf("%s is not at its conventional path (%s); `kagaz lint --fix` or `kagaz move` will re-file it",
				prop.Source, prop.Dest))
		}
	}
	payload.Sidecars = written
	payload.Reindexed = payload.Reindexed[:0]
	for _, p := range written {
		payload.Reindexed = append(payload.Reindexed, sidecar.DocumentFor(p))
	}
	return rt.Emit(&Response{
		Command: "ingest", Status: StatusOK, Payload: payload,
		Warnings: warnings, Human: humanIngest,
	})
}

// vaultDocuments lists every document currently filed in the vault.
func vaultDocuments(ctx context.Context, cfg *config.Config) ([]string, error) {
	searcher, err := search.New(cfg)
	if err != nil {
		return nil, err
	}
	tree, err := searcher.Scan(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(tree.Documents))
	for i := range tree.Documents {
		if tree.Documents[i].Evicted {
			continue
		}
		out = append(out, tree.Documents[i].Path)
	}
	return out, nil
}

func previewIngest(w io.Writer, payload any) error {
	p, ok := payload.(IngestPayload)
	if !ok {
		return fmt.Errorf("ingest: unexpected payload %T", payload)
	}
	if len(p.Proposals) == 0 {
		fmt.Fprintln(w, "nothing to propose")
		return nil
	}
	advice := map[string]Guidance{}
	for _, g := range p.Guidance {
		advice[g.Source] = g
	}
	for _, prop := range p.Proposals {
		fmt.Fprint(w, tidyReasons(prop.Preview()))
		if g, ok := advice[prop.Source]; ok {
			fmt.Fprintf(w, "   why   %s\n", g.Cause)
			fmt.Fprintf(w, "   next  %s\n", g.NextStep)
		}
	}
	return nil
}

func previewReindex(w io.Writer, payload any) error {
	p, ok := payload.(IngestPayload)
	if !ok {
		return fmt.Errorf("ingest: unexpected payload %T", payload)
	}
	fmt.Fprintf(w, "regenerate %d sidecar(s):\n", len(p.Reindexed))
	for _, path := range p.Reindexed {
		fmt.Fprintf(w, "  %s\n", path)
	}
	return nil
}

func humanIngest(w io.Writer, payload any) error {
	p, ok := payload.(IngestPayload)
	if !ok {
		return fmt.Errorf("ingest: unexpected payload %T", payload)
	}
	if len(p.Reindexed) > 0 || len(p.Sidecars) > 0 && !p.Executed {
		fmt.Fprintf(w, "regenerated %d sidecar(s)\n", len(p.Sidecars))
		return nil
	}
	if !p.Executed {
		if len(p.Proposals) == 0 {
			fmt.Fprintln(w, "nothing to propose")
			return nil
		}
		return previewIngest(w, payload)
	}
	for _, m := range p.Filed {
		fmt.Fprintf(w, "filed %s\n   -> %s\n", filepath.Base(m.From), m.To)
	}
	fmt.Fprintf(w, "\n%d document(s) filed, %d sidecar(s) written\n", len(p.Filed), len(p.Sidecars))
	if p.Manifest != "" {
		fmt.Fprintf(w, "manifest: %s (reverse with `kagaz rollback %s`)\n", p.Manifest, filepath.Base(p.Manifest))
	}
	return nil
}

// summarizeProposal is the one-line form used by `watch`, which reports many
// small batches rather than one reviewed batch.
func summarizeProposal(p ingest.Proposal) string {
	if p.Skip {
		return tidyReasons(fmt.Sprintf("%s: skipped (%s)", filepath.Base(p.Source), p.SkipReason))
	}
	return fmt.Sprintf("%s -> %s [%s %.2f]", filepath.Base(p.Source), p.Dest, p.DocType, p.Confidence)
}

// nowStamp is the date form sidecars record.
func nowStamp() string { return time.Now().Format("2006-01-02") }
