// Package index regenerates a vault's two generated documents: INDEX.md, a
// human-readable snapshot of what the vault holds and how to query it, and
// AGENTS.md, the same vault explained to an AI agent, rendered from
// docs/AGENTS.template.md so it can never drift from the documented contract.
//
// Everything this package emits is byte-stable: the same tree and the same
// vault.yaml always produce the same bytes. No timestamp, no duration, no
// absolute path from the machine that generated it, and no map iterated in Go's
// randomised order ever reaches the output — every list is sorted before it is
// rendered. Golden tests depend on this, and so does anyone keeping a vault in
// git, for whom a regenerated file that differs only in a timestamp is a
// diff-shaped lie.
package index

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkagaz/kagaz/internal/vaultkit/config"
	"github.com/getkagaz/kagaz/internal/vaultkit/conventions"
	"github.com/getkagaz/kagaz/internal/vaultkit/doctypes"
	"github.com/getkagaz/kagaz/internal/vaultkit/fycal"
	"github.com/getkagaz/kagaz/internal/vaultkit/search"
	"github.com/getkagaz/kagaz/internal/vaultkit/tags"
)

// File names written at the vault root.
const (
	IndexFile  = "INDEX.md"
	AgentsFile = "AGENTS.md"
)

// Banner is the generated-file marker both documents carry. It is the first
// thing a human or an agent reads, and the reason a hand-edit is safe to
// overwrite.
const Banner = "<!-- GENERATED by `kagaz index`. Do not hand-edit; regenerate with `kagaz index`. -->"

// noneYet is what an empty list renders as. An empty string or a removed
// section reads as a rendering bug; this reads as "there is nothing here yet",
// which is the truth.
const noneYet = "_(none yet)_"

// Generator renders the generated documents for one vault.
type Generator struct {
	cfg     *config.Config
	conv    *conventions.Conventions
	catalog *doctypes.Catalog
	vocab   *tags.Vocabulary
	cal     fycal.Calendar
}

// New builds a Generator for a vault.
func New(cfg *config.Config) (*Generator, error) {
	conv, err := conventions.New(cfg)
	if err != nil {
		return nil, err
	}
	cat, err := doctypes.Resolve(cfg)
	if err != nil {
		return nil, err
	}
	return &Generator{
		cfg:     cfg,
		conv:    conv,
		catalog: cat,
		vocab:   tags.NewVocabulary(cfg),
		cal:     fycal.New(cfg.FiscalYear.StartMonth, cfg.FiscalYear.LabelFormat),
	}, nil
}

// Generate scans the vault and writes both documents, returning the paths
// written in the order INDEX.md, AGENTS.md.
func Generate(ctx context.Context, cfg *config.Config) ([]string, error) {
	s, err := search.New(cfg)
	if err != nil {
		return nil, err
	}
	tree, err := s.Scan(ctx)
	if err != nil {
		return nil, err
	}
	g, err := New(cfg)
	if err != nil {
		return nil, err
	}
	return g.Write(tree)
}

// Write renders both documents and writes them at the vault root.
func (g *Generator) Write(tree *search.Tree) ([]string, error) {
	idx, err := g.Index(tree)
	if err != nil {
		return nil, err
	}
	agents, err := g.Agents(tree)
	if err != nil {
		return nil, err
	}
	idxPath := filepath.Join(g.cfg.VaultRoot, IndexFile)
	agentsPath := filepath.Join(g.cfg.VaultRoot, AgentsFile)
	if err := os.WriteFile(idxPath, []byte(idx), 0o644); err != nil {
		return nil, err
	}
	if err := os.WriteFile(agentsPath, []byte(agents), 0o644); err != nil {
		return []string{idxPath}, err
	}
	return []string{idxPath, agentsPath}, nil
}

// VaultName is the short human label for the vault: the folder name of its
// root. Never the absolute path — that is specific to one machine and would
// make the generated files unstable across a sync.
func (g *Generator) VaultName() string {
	name := filepath.Base(filepath.Clean(g.cfg.VaultRoot))
	if name == "." || name == string(filepath.Separator) || name == "" {
		return "vault"
	}
	return name
}

// Index renders INDEX.md.
func (g *Generator) Index(tree *search.Tree) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "# INDEX — %s\n\n", g.VaultName())
	b.WriteString(Banner + "\n\n")
	b.WriteString("A snapshot of what this vault holds and how to query it. It is regenerated by\n" +
		"`kagaz index`; for anything current — lint status, a live search — call\n" +
		"`kagaz find --json` or `kagaz lint --json` instead of trusting this file.\n\n")

	docs := tree.Documents
	fmt.Fprintf(&b, "- Documents: %d\n", len(docs))
	fmt.Fprintf(&b, "- Categories with documents: %d of %d configured\n", len(countBy(docs, categoryKey)), len(g.cfg.Structure))
	fmt.Fprintf(&b, "- Documents with a sidecar: %d\n", countIf(docs, func(d *search.Document) bool { return d.HasSidecar }))
	fmt.Fprintf(&b, "- Documents whose filename matches the grammar: %d\n", countIf(docs, func(d *search.Document) bool { return d.Parsed }))
	if n := countIf(docs, func(d *search.Document) bool { return d.Evicted }); n > 0 {
		fmt.Fprintf(&b, "- Documents evicted to iCloud (bytes not on this machine): %d\n", n)
	}
	if n := len(tree.OrphanSidecars); n > 0 {
		fmt.Fprintf(&b, "- Sidecars with no document: %d (see `kagaz lint`)\n", n)
	}
	b.WriteString("\n## Documents by category\n\n")
	b.WriteString(g.categoryTable(docs))

	b.WriteString("\n## Documents by doctype\n\n")
	b.WriteString(g.doctypeTable(docs))

	b.WriteString("\n## Fiscal year\n\n")
	b.WriteString(g.fiscalNote() + "\n")

	b.WriteString("\n## Tag vocabulary\n\n")
	b.WriteString(strings.TrimRight(g.tagVocabulary(), "\n") + "\n")

	b.WriteString("\n## Tags in use\n\n")
	b.WriteString(strings.TrimRight(g.tagsInUse(docs), "\n") + "\n")

	b.WriteString("\n## Smart-folder queries\n\n")
	b.WriteString("Run these from the vault root; `mdfind` needs Spotlight indexing enabled for\n" +
		"this folder. `kagaz find` applies the same filters and does not need Spotlight.\n\n")
	b.WriteString(strings.TrimRight(g.mdfindQueries(), "\n") + "\n")

	return b.String(), nil
}

// categoryKey groups a document by the category folder it was found under.
func categoryKey(d *search.Document) string {
	if d.Category == "" {
		return "(outside any configured category)"
	}
	return d.Category
}

// doctypeKey groups a document by its doctype, naming the absence explicitly.
func doctypeKey(d *search.Document) string {
	if dt := d.DocType(); dt != "" {
		return dt
	}
	return "(unrecognised)"
}

// categoryTable renders one row per configured category, plus a row for
// anything found outside them. Every configured category is listed even at zero
// documents: a category that vanishes from the table when it empties reads as a
// rendering bug.
func (g *Generator) categoryTable(docs []search.Document) string {
	counts := countBy(docs, categoryKey)
	names := make([]string, 0, len(g.cfg.Structure))
	for name := range g.cfg.Structure {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("| Category | Folder | Layout | Documents |\n|---|---|---|---|\n")
	for _, name := range names {
		cat := g.cfg.Structure[name]
		fmt.Fprintf(&b, "| `%s` | `%s/` | `%s` | %d |\n", name, cat.Path, cat.Layout, counts[name])
	}
	for _, extra := range sortedKeys(counts) {
		if _, configured := g.cfg.Structure[extra]; !configured {
			fmt.Fprintf(&b, "| %s | — | — | %d |\n", extra, counts[extra])
		}
	}
	return b.String()
}

// doctypeTable renders the doctypes that actually occur, sorted by name.
func (g *Generator) doctypeTable(docs []search.Document) string {
	counts := countBy(docs, doctypeKey)
	if len(counts) == 0 {
		return noneYet + "\n"
	}
	var b strings.Builder
	b.WriteString("| Doctype | Category | Documents |\n|---|---|---|\n")
	for _, name := range sortedKeys(counts) {
		category := "—"
		if c, ok := g.catalog.CategoryOf(name); ok {
			category = "`" + c + "`"
		}
		label := name
		if g.catalog.Has(name) {
			label = "`" + name + "`"
		}
		fmt.Fprintf(&b, "| %s | %s | %d |\n", label, category, counts[name])
	}
	return b.String()
}

// fiscalNote is one sentence describing fiscal_year.start_month and
// label_format, illustrated with a fixed sample year so the sentence is
// identical on every run.
func (g *Generator) fiscalNote() string {
	const sample = 2026
	label := g.cal.YearStarting(sample).Label()
	month := monthName(g.cfg.FiscalYear.StartMonth)
	if g.cfg.FiscalYear.StartMonth == 1 {
		return fmt.Sprintf("The fiscal year is the calendar year (it starts in %s) and is labelled `%s`, "+
			"which is also the `{FY}` folder name and the `fy%d` tag.", month, label, sample)
	}
	return fmt.Sprintf("The fiscal year starts in %s and is labelled `%s`, so a document dated %s %d or later "+
		"belongs to `%s` — that label is also the `{FY}` folder name, and `%s` is its tag.",
		month, label, month, sample, label, g.cal.YearStarting(sample).Tag())
}

func monthName(m int) string {
	names := []string{"January", "February", "March", "April", "May", "June",
		"July", "August", "September", "October", "November", "December"}
	if m < 1 || m > 12 {
		return "January"
	}
	return names[m-1]
}

// tagVocabulary lists the controlled vocabulary grouped by kind.
func (g *Generator) tagVocabulary() string {
	kinds := []struct {
		kind  tags.Kind
		label string
	}{
		{tags.KindPerson, "person"},
		{tags.KindCompany, "company"},
		{tags.KindArea, "area"},
		{tags.KindFiscalYear, "fiscal-year"},
		{tags.KindLifecycle, "lifecycle"},
	}
	var b strings.Builder
	for _, k := range kinds {
		list := g.vocab.OfKind(k.kind)
		fmt.Fprintf(&b, "- **%s** — %s\n", k.label, joinCode(list))
	}
	return b.String()
}

// tagsInUse counts the tags actually applied to documents. On a filesystem with
// no extended-attribute support this is simply empty, which is reported as such
// rather than as an error.
func (g *Generator) tagsInUse(docs []search.Document) string {
	counts := map[string]int{}
	for i := range docs {
		for _, t := range docs[i].Tags {
			counts[t]++
		}
	}
	if len(counts) == 0 {
		return "_No Finder tags are set on any document in this vault yet._\n"
	}
	var b strings.Builder
	b.WriteString("| Tag | Kind | Documents |\n|---|---|---|\n")
	for _, t := range sortedKeys(counts) {
		fmt.Fprintf(&b, "| `%s` | %s | %d |\n", t, g.vocab.Kind(t), counts[t])
	}
	return b.String()
}

// mdfindQueries renders ready-to-paste Spotlight queries as one fenced block.
//
// Queries are emitted for the bounded parts of the vocabulary (lifecycle and
// area tags) and as a placeholder form for the parts that grow with the vault
// (people, companies, fiscal years) — a vault with three hundred companies does
// not want three hundred lines here, and truncating a list would make the file
// depend on how much of it fits rather than on what the vault contains.
func (g *Generator) mdfindQueries() string {
	var b strings.Builder
	b.WriteString("```\n")
	b.WriteString("# every document carrying a lifecycle tag\n")
	lifecycle := g.vocab.OfKind(tags.KindLifecycle)
	if len(lifecycle) == 0 {
		b.WriteString("# (this vault defines no lifecycle tags)\n")
	}
	for _, t := range lifecycle {
		fmt.Fprintf(&b, "mdfind -onlyin . '%s'\n", search.TagQuery(t))
	}
	areas := g.vocab.OfKind(tags.KindArea)
	if len(areas) > 0 {
		b.WriteString("\n# by area\n")
		for _, t := range areas {
			fmt.Fprintf(&b, "mdfind -onlyin . '%s'\n", search.TagQuery(t))
		}
	}
	b.WriteString("\n# by person, company or fiscal year: substitute a tag from the vocabulary above\n")
	fmt.Fprintf(&b, "mdfind -onlyin . '%s'\n", search.TagQuery("<tag>"))
	b.WriteString("\n# two tags at once (this vault's tags are ANDed, like kagaz find --tag a --tag b)\n")
	fmt.Fprintf(&b, "mdfind -onlyin . '%s'\n", search.MDFindExpr(search.Query{Tags: []string{"<tag>", "<other-tag>"}}))
	b.WriteString("\n# free text in a document's indexed contents or its name\n")
	fmt.Fprintf(&b, "mdfind -onlyin . '%s'\n", search.MDFindExpr(search.Query{Text: "<text>"}))
	b.WriteString("```\n")
	return b.String()
}

// joinCode renders a list as inline code, or the "(none yet)" marker.
func joinCode(list []string) string {
	if len(list) == 0 {
		return noneYet
	}
	out := make([]string, len(list))
	for i, s := range list {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

func countBy(docs []search.Document, key func(*search.Document) string) map[string]int {
	counts := map[string]int{}
	for i := range docs {
		counts[key(&docs[i])]++
	}
	return counts
}

func countIf(docs []search.Document, pred func(*search.Document) bool) int {
	n := 0
	for i := range docs {
		if pred(&docs[i]) {
			n++
		}
	}
	return n
}

// sortedKeys returns a map's keys in sorted order. Every list this package
// renders goes through here or through sort directly; nothing is emitted
// straight out of a map range.
func sortedKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
